=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/lib/I2CE_Configuration.dtd
<!ELEMENT I2CEConfiguration (metadata,(eraseVals|erase)*,configurationGroup?)>
<!ATTLIST I2CEConfiguration name NMTOKEN #REQUIRED>
<!ELEMENT metadata
          (displayName,className?,category?,description?,longDescription?,creator?,email?,link?,version,(enable|requirement|conflict|path)*,priority?)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ELEMENT path (value*)>
<!ATTLIST path name NMTOKEN #REQUIRED>
<!ELEMENT enable EMPTY>
<!ATTLIST enable name NMTOKEN #REQUIRED>
<!ELEMENT requirement (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST requirement name NMTOKEN #REQUIRED>
<!ATTLIST requirement external NMTOKEN #IMPLIED>
<!ELEMENT conflict (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST conflict name NMTOKEN #REQUIRED>
<!ATTLIST conflict external NMTOKEN #IMPLIED>
<!ELEMENT erase (atLeast|atMost|exactly|greaterThan|lessThan)>
<!ATTLIST erase path CDATA #REQUIRED>
<!ELEMENT eraseVals ((atLeast|atMost|exactly|greaterThan|lessThan),value*) >
<!ATTLIST eraseVals path CDATA #REQUIRED>
<!ELEMENT configurationGroup (displayName?,description?,version?,status*,(configurationGroup|configuration|eraseVals|erase)*)>
<!ATTLIST configurationGroup name NMTOKEN  #REQUIRED>
<!ATTLIST configurationGroup path CDATA #IMPLIED>
<!ATTLIST configurationGroup config NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup locale NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup binary NMTOKEN #IMPLIED>
<!ELEMENT configuration (displayName?,description?,version?,status*,value*,(eraseVals|erase)*)>
<!ATTLIST configuration name NMTOKEN #REQUIRED>
<!ATTLIST configuration path CDATA #IMPLIED>
<!ATTLIST configuration values NMTOKEN "single">
<!ATTLIST configuration type NMTOKEN "string">
<!ATTLIST configuration config NMTOKEN #IMPLIED>
<!ATTLIST configuration locale NMTOKEN #IMPLIED>
<!ATTLIST configuration binary NMTOKEN #IMPLIED>
<!ATTLIST configuration encoding NMTOKEN #IMPLIED>
<!ELEMENT displayName (#PCDATA)>
<!ATTLIST displayName locale NMTOKEN #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT longDescription (#PCDATA)>
<!ATTLIST longDescription locale NMTOKEN #IMPLIED>
<!ATTLIST description locale NMTOKEN #IMPLIED>
<!ELEMENT className (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category locale NMTOKEN #IMPLIED>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT value (#PCDATA)> 
<!ATTLIST value locale NMTOKEN #IMPLIED>
<!ELEMENT eval EMPTY> 
<!ELEMENT atLeast EMPTY> 
<!ATTLIST atLeast version CDATA #REQUIRED>
<!ELEMENT greaterThan EMPTY> 
<!ATTLIST greaterThan version CDATA #REQUIRED>
<!ELEMENT atMost EMPTY> 
<!ATTLIST atMost version CDATA #REQUIRED>
<!ELEMENT lessThan EMPTY> 
<!ATTLIST lessThan version CDATA #REQUIRED> 
<!ELEMENT exactly EMPTY> 
<!ATTLIST exactly version CDATA #REQUIRED>
<!ELEMENT visibility (#PCDATA)> 
<!ELEMENT status (#PCDATA)>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-qualify/modules/QualifyCustomReports/Reports/Registration/configs/nl/ihris-qualify-CustomReports-registration.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="ihris-qualify-CustomReports-registration" path="//modules/CustomReports">
  <metadata>
    <version>4.1.0.1</version>
  </metadata>
  <configurationGroup name="ihris-qualify-CustomReports-registration" path="//modules/CustomReports" locale="nl">
    <version>4.1.0.1</version>
    <configurationGroup name="relationship-registration" path="relationships/registration">
      <configuration name="display_name" locale="nl">
        <value>Registratie</value>
      </configuration>
      <configuration name="description" locale="nl">
        <value>Relatie voor rapportages over registraties.</value>
      </configuration>
      <configurationGroup name="joins">
        <configurationGroup name="training">
          <configuration name="description" locale="nl">
            <value>De opleiding die gekoppeld is aan deze registratie.</value>
          </configuration>
          <configuration name="display_name" locale="nl">
            <value>Opleiding</value>
          </configuration>
          <configurationGroup name="joins">
            <configurationGroup name="cadre">
              <configuration name="description" locale="nl">
                <value>Het kader dat bij deze opleiding hoort.</value>
              </configuration>
              <configuration name="display_name" locale="nl">
                <value>Kader</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="person">
              <configuration name="description" locale="nl">
                <value>De persoon die deze opleiding gevolgd heeft.</value>
              </configuration>
              <configuration name="display_name" locale="nl">
                <value>Persoon</value>
              </configuration>
              <configurationGroup name="joins">
                <configurationGroup name="personal_contact">
                  <configuration name="description" locale="nl">
                    <value>De persoonlijke contactgegevens voor deze persoon.</value>
                  </configuration>
                  <configuration name="display_name" locale="nl">
                    <value>Persoonlijk contactpersoon</value>
                  </configuration>
                </configurationGroup>
              </configurationGroup>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="report-registration" path="reports/registration">
      <configurationGroup name="meta">
        <configuration name="display_name" locale="nl">
          <value>Registratierapportage</value>
        </configuration>
        <configuration name="description" locale="nl">
          <value>Rapportages gebaseerd op registraties in het systeem.</value>
        </configuration>
        <configuration name="category" locale="nl">
          <value>Opleidingsrapportages</value>
        </configuration>
      </configurationGroup>
      <configurationGroup name="reporting_forms">
        <configurationGroup name="primary_form">
          <configurationGroup name="fields">
            <configurationGroup name="registration_number">
              <configuration name="header" locale="nl">
                <value>Registratienummer</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="registration_date">
              <configuration name="header" locale="nl">
                <value>Registratiedatum</value>
              </configuration>
              <configurationGroup name="limits">
                <configurationGroup name="greaterthan_equals">
                  <configuration name="header" locale="nl">
                    <value>Registratiedatum na</value>
                  </configuration>
                </configurationGroup>
                <configurationGroup name="lessthan_equals">
                  <configuration name="header" locale="nl">
                    <value>Registratiedatum voor</value>
                  </configuration>
                </configurationGroup>
              </configurationGroup>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="training">
          <configurationGroup name="fields">
            <configurationGroup name="cadre">
              <configurationGroup name="limits">
                <configurationGroup name="equals">
                  <configuration name="header" locale="nl">
                    <value>Kader</value>
                  </configuration>
                </configurationGroup>
              </configurationGroup>
              <configuration name="header" locale="nl">
                <value>Opleidingkader-ID</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="intake_date">
              <configurationGroup name="limits">
                <configurationGroup name="greaterthan_equals">
                  <configuration name="header" locale="nl">
                    <value>Opnamedatum na</value>
                  </configuration>
                </configurationGroup>
                <configurationGroup name="lessthan_equals">
                  <configuration name="header" locale="nl">
                    <value>Opnamedatum voor</value>
                  </configuration>
                </configurationGroup>
              </configurationGroup>
              <configuration name="header" locale="nl">
                <value>Opnamedatum</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="person">
          <configurationGroup name="fields">
            <configurationGroup name="surname">
              <configuration name="header" locale="nl">
                <value>Achternaam</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="firstname">
              <configuration name="header" locale="nl">
                <value>Voornaam</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="personal_contact">
          <configurationGroup name="fields">
            <configurationGroup name="address">
              <configuration name="header" locale="nl">
                <value>Postadres</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="cadre">
          <configurationGroup name="fields">
            <configurationGroup name="name">
              <configuration name="header" locale="nl">
                <value>Kader</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="reportView-registration" path="reportViews/registration">
      <configuration name="description" locale="nl">
        <value>Een lijst met alle geregistreerde gezondheidswerkers.</value>
      </configuration>
      <configuration name="display_name" locale="nl">
        <value>Geregistreerde gezondheidswerkers</value>
      </configuration>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/TemplateData/modules/Options/Options.xml
<?xml version="1.0"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Options">
  <metadata>
    <displayName>I2CE Options Data</displayName>
    <className>I2CE_Template_Options</className>
    <category>Base System Component</category>
    <description>Adds options data to the template</description>
    <creator>Intrahealth Informatics</creator>
    <email>hris@capacityproject.org</email>
    <link>https://launchpad.net/i2ce</link>
    <version>4.3.0</version>
    <requirement name="I2CE">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="template-data">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
  </metadata>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/TemplateData/modules/Tags/Tags.xml
<?xml version="1.0"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Tags">
  <metadata>
    <displayName>Tags</displayName>
    <className>I2CE_Module_Tags</className>
    <category>Base System Component</category>
    <description>Adds module and script tag processing to the template</description>
    <creator>Intrahealth Informatics</creator>
    <email>hris@capacityproject.org</email>
    <link>https://launchpad.net/i2ce</link>
    <version>4.3.0</version>
    <requirement name="I2CE">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="template-data">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="DisplayData">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <priority>49</priority>
  </metadata>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/Forms/modules/Lists/configs/uk/Lists.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Lists" path="/I2CE/">
  <metadata>
    <version>4.3.3.0.1</version>
  </metadata>
  <configurationGroup name="Lists" path="/I2CE/" locale="uk">
    <version>4.3.0.1</version>
    <configurationGroup name="auto_list" path="/I2CE/page/auto_list">
      <configuration name="title" locale="uk" values="single" type="string">
        <value>Адміністрування списків баз даних</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="Lists" path="/modules/Lists">
      <configuration name="messages" type="delimited" values="many" locale="uk">
        <value>other_lists:Інші списки</value>
        <value>title:Переглянути %s</value>
        <value>edit_title:Додати/оновити %s</value>
        <value>edit_text:Оновити цю інформацію</value>
        <value>add_text:Додати новий %s</value>
        <value>add_new:Додати нову</value>
        <value>select_text:Виберіть інший %s</value>
        <value>menu_title:Адміністрування списків баз даних</value>
        <value>remap_field_text:Перепризначити поле %1$s в %2$s (%3$s збігів)</value>
        <value>remap_text:Задати перерозподіл даних</value>
        <value>view_remap_text:Переглянути перерозподіл даних</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="invalid_messages" path="/modules/forms/invalid_field_messages" locale="uk">
      <configuration name="unique_fields" values="single" type="string">
        <value>Це має бути унікальним і інший запис має це значення для заданого значення полів:</value>
      </configuration>
      <configuration name="unique_field" values="single" type="string">
        <value>Це має бути унікальним і інший запис має це значення для заданого значення поля:</value>
      </configuration>
      <configuration name="unique" values="single" type="string">
        <value>Це має бути унікальним і інший запис має це значення.</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="template_text" path="/modules/forms/template_text">
      <configuration name="blank" values="single" locale="uk" type="string">
        <value>Виберіть один</value>
      </configuration>
      <configuration name="loading" values="single" locale="uk" type="string"></configuration>
      <configuration name="no_results" values="single" locale="uk" type="string"></configuration>
      <configuration name="default_display" values="single" locale="uk" type="string"></configuration>
      <configuration name="clear_display" values="single" locale="uk" type="string"></configuration>
    </configurationGroup>
    <configurationGroup name="formClasses" path="/modules/forms/formClasses">
      <configurationGroup name="I2CE_List">
        <configurationGroup name="fields">
          <configurationGroup name="remap">
            <configuration name="headers" type="delimited" locale="uk" values="single">
              <value>default:Перерозподілене значення</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="i2ce_hidden">
            <configuration name="headers" type="delimited" locale="uk" values="single">
              <value>default:Приховати</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="I2CE_SimpleList">
        <configurationGroup name="fields">
          <configurationGroup name="name">
            <configuration name="headers" type="delimited" locale="uk" values="single">
              <value>default:Ім'я</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="I2CE_SimpleCodedList">
        <configurationGroup name="fields">
          <configurationGroup name="code">
            <configuration name="headers" type="delimited" locale="uk" values="single">
              <value>default:Код</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="uk">
      <configuration name="can_hide_list_members" values="single" type="string">
        <value>Можна приховати список членів</value>
      </configuration>
      <configuration name="can_edit_database_lists" values="single" type="string">
        <value>Можна змінити деякі списки, збережені в базі даних</value>
      </configuration>
      <configuration name="can_edit_all_database_lists" values="single" type="string">
        <value>Можна редагувати всі списки, які зберігаються в базі даних</value>
      </configuration>
      <configuration name="can_view_database_lists" values="single" type="string">
        <value>Можна переглянути деякі списки, які зберігаються в базі даних</value>
      </configuration>
      <configuration name="can_view_all_database_lists" values="single" type="string">
        <value>Можна переглянути всі списки, які зберігаються в базі даних</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="pages" path="/I2CE/page">
      <configurationGroup name="view_list">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="uk" type="string">
            <value>Перегляд списку</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/Forms/modules/FormStorage/modules/FormStorageMultiFlat/MultiFlat.xml
<?xml version="1.0"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="forms-storage-multiflat">
  <metadata>
    <displayName>Form Storage - Multi Flat</displayName>
    <category>Base System Component</category>
    <description>A module that enables aggregated storage of Forms from a flat fixed database structure.</description>
    <creator>Carl Leitner</creator>
    <email>litlfred@ibiblio.org</email>
    <link>https://launchpad.net/i2ce</link>
    <version>4.3.0</version>
    <requirement name="forms-storage">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="Lists">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <path name="classes">
      <value>./lib</value>
    </path>
  </metadata>
  <configurationGroup name="forms-storage-multiflat" path="/">
    <configuration name="" path="/modules/forms/storage_options/multi_flat/componentized" values="single" type="string">
      <version>4.0.1</version>
      <value>1</value>
    </configuration>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Facility/modules/InfoManStorage_FacilityMap/configs/en_US/InfoManStorage_FacilityMap.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="InfoManStorate_FacilityMap" path="/">
  <metadata>
    <version>4.3.0</version>
  </metadata>
  <configurationGroup name="InfoManStorate_FacilityMap" path="/" locale="en_US">
    <version>4.3.0</version>
    <configurationGroup name="csd_faciliy_field" path="/modules/forms/formClasses/iHRIS_Facility/fields/csd_facility">
      <configuration name="headers" type="delimited" locale="en_US">
        <value>default:CSD Facility</value>
      </configuration>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/ID/configs/br/ID.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonID" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonID" path="/I2CE" locale="br">
    <version>4.2.1.0.1</version>
    <configurationGroup name="invalid_formfield_message" path="/modules/forms/formfield_messages" locale="br">
      <configuration name="exp_date" path="person_id/expiration_date/bad_date" locale="br">
        <value>An deiziad termen a zle bezañ goude an deiziad embann</value>
      </configuration>
      <configuration name="wrong_pattern" path="person_id/id_num/wrong_pattern" locale="br"></configuration>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="br">
      <configuration name="person_can_view_child_form_person_id" locale="br">
        <value>A c'hall diskwel furmskrid bugel ID un den</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_id" locale="br">
        <value>A c'hall kemmañ furmskridoù bugel ID un den</value>
      </configuration>
      <configuration name="can_edit_database_list_id_type" locale="br">
        <value>A c'hall kemmañ roll diaz titouroù ar seurtoù ID</value>
      </configuration>
      <configuration name="can_view_database_list_id_type" locale="br">
        <value>A c'hall diskwel roll diaz titouroù ar seurtoù ID</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="person_id">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="br">
            <value>Ouzhpennañ/Hizivaat anaout</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms/forms">
      <configurationGroup name="id_type">
        <configuration name="display" values="single" locale="br">
          <value>Doare anaout</value>
        </configuration>
      </configurationGroup>
      <configurationGroup name="person_id">
        <configuration name="display" values="single" locale="br">
          <value>anaout an den</value>
        </configuration>
        <configurationGroup name="meta">
          <configuration name="description" locale="br">
            <value>Titouroù diazez war un anaoudadur evit un den zo er furmskrid-mañ</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms/formClasses">
      <configurationGroup name="iHRIS_PersonID">
        <configurationGroup name="fields">
          <configurationGroup name="id_type">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Doare anaout</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="id_num">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Niverenn-anaout</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="issue_date">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Deiziad embann</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="expiration_date">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Deiziad termen</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="country">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Bro embann</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="place">
            <configuration name="headers" type="delimited" locale="br">
              <value>default:Lec'h embann</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="iHRIS_PersonID_Type">
        <configurationGroup name="fields">
          <configurationGroup name="pattern">
            <configuration name="headers" type="delimited" locale="br"></configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/CSD/modules/CSDCache/CSD_Cache.xml
<?xml version="1.0"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="csd_cache">
  <metadata>
    <displayName>CSD Cache</displayName>
    <className>iHRIS_Module_CSDCache</className>
    <category>Data Standards</category>
    <description>Allows caching of health worker data (or other entities) in the CSD compliant fashion into a table for quick responses to Query for Updated Serivces transactions</description>
    <creator>Carl Leitner</creator>
    <email>litlfred@ibiblio.org</email>
    <link>https://launchpad.net/common</link>
    <version>4.3.0</version>
    <path name="configs">
      <value>./configs</value>
    </path>
    <requirement name="formRelationships">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="UUID_map">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="SVS">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <requirement name="iso-country">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <path name="templates">
      <value>./templates</value>
    </path>
    <path name="sql">
      <value>./sql</value>
    </path>
    <requirement name="pages">
      <atLeast version="4.3" />
      <lessThan version="4.4" />
    </requirement>
    <path name="classes">
      <value>./lib</value>
    </path>
    <path name="modules">
      <value>./modules</value>
    </path>
    <priority>150</priority>
  </metadata>
  <configurationGroup name="CSD_Cache" path="/">
    <configurationGroup name="csd_cache_admin" path="/I2CE/command_line/csd_cache">
      <version>4.2.0.5</version>
      <configuration name="class" values="single">
        <value>iHRIS_Page_CSDCacheAdmin</value>
      </configuration>
      <configuration name="style" values="single">
        <value>action</value>
      </configuration>
      <configurationGroup name="args">
        <configuration name="tasks" values="many">
          <value>csd_cache_admin</value>
        </configuration>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="csd_cache_admin" path="/I2CE/page/csd_cache">
      <version>4.2.0.3</version>
      <configuration name="class" values="single">
        <value>iHRIS_Page_CSDCacheAdmin</value>
      </configuration>
      <configuration name="style" values="single">
        <value>shell</value>
      </configuration>
      <configurationGroup name="args">
        <configuration name="defaultHTMLFile" values="many">
          <value>csd_cache_admin_menu.html</value>
        </configuration>
        <configuration name="tasks" values="many">
          <value>csd_cache_admin</value>
        </configuration>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="en_US">
      <version>4.2.0.3</version>
      <configuration name="csd_cache_admin" locale="en_US">
        <value>Can administer caches of CSD Export</value>
      </configuration>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>
