=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/lib/I2CE_Configuration.dtd
<!ELEMENT I2CEConfiguration (metadata,(eraseVals|erase)*,configurationGroup?)>
<!ATTLIST I2CEConfiguration name NMTOKEN #REQUIRED>
<!ELEMENT metadata
          (displayName,className?,category?,description?,longDescription?,creator?,email?,link?,version,(enable|requirement|conflict|path)*,priority?)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ELEMENT path (value*)>
<!ATTLIST path name NMTOKEN #REQUIRED>
<!ELEMENT enable EMPTY>
<!ATTLIST enable name NMTOKEN #REQUIRED>
<!ELEMENT requirement (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST requirement name NMTOKEN #REQUIRED>
<!ATTLIST requirement external NMTOKEN #IMPLIED>
<!ELEMENT conflict (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST conflict name NMTOKEN #REQUIRED>
<!ATTLIST conflict external NMTOKEN #IMPLIED>
<!ELEMENT erase (atLeast|atMost|exactly|greaterThan|lessThan)>
<!ATTLIST erase path CDATA #REQUIRED>
<!ELEMENT eraseVals ((atLeast|atMost|exactly|greaterThan|lessThan),value*) >
<!ATTLIST eraseVals path CDATA #REQUIRED>
<!ELEMENT configurationGroup (displayName?,description?,version?,status*,(configurationGroup|configuration|eraseVals|erase)*)>
<!ATTLIST configurationGroup name NMTOKEN  #REQUIRED>
<!ATTLIST configurationGroup path CDATA #IMPLIED>
<!ATTLIST configurationGroup config NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup locale NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup binary NMTOKEN #IMPLIED>
<!ELEMENT configuration (displayName?,description?,version?,status*,value*,(eraseVals|erase)*)>
<!ATTLIST configuration name NMTOKEN #REQUIRED>
<!ATTLIST configuration path CDATA #IMPLIED>
<!ATTLIST configuration values NMTOKEN "single">
<!ATTLIST configuration type NMTOKEN "string">
<!ATTLIST configuration config NMTOKEN #IMPLIED>
<!ATTLIST configuration locale NMTOKEN #IMPLIED>
<!ATTLIST configuration binary NMTOKEN #IMPLIED>
<!ATTLIST configuration encoding NMTOKEN #IMPLIED>
<!ELEMENT displayName (#PCDATA)>
<!ATTLIST displayName locale NMTOKEN #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT longDescription (#PCDATA)>
<!ATTLIST longDescription locale NMTOKEN #IMPLIED>
<!ATTLIST description locale NMTOKEN #IMPLIED>
<!ELEMENT className (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category locale NMTOKEN #IMPLIED>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT value (#PCDATA)> 
<!ATTLIST value locale NMTOKEN #IMPLIED>
<!ELEMENT eval EMPTY> 
<!ELEMENT atLeast EMPTY> 
<!ATTLIST atLeast version CDATA #REQUIRED>
<!ELEMENT greaterThan EMPTY> 
<!ATTLIST greaterThan version CDATA #REQUIRED>
<!ELEMENT atMost EMPTY> 
<!ATTLIST atMost version CDATA #REQUIRED>
<!ELEMENT lessThan EMPTY> 
<!ATTLIST lessThan version CDATA #REQUIRED> 
<!ELEMENT exactly EMPTY> 
<!ATTLIST exactly version CDATA #REQUIRED>
<!ELEMENT visibility (#PCDATA)> 
<!ELEMENT status (#PCDATA)>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/SelfService/configs/uk/SelfService.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="SelfService" path="/">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="SelfService" path="/" locale="uk">
    <version>4.2.0.1.1</version>
    <configurationGroup name="SS" path="/modules/SelfService">
      <configurationGroup name="page">
        <configurationGroup name="view">
          <configurationGroup name="args">
            <configuration name="title" locale="uk">
              <value>Перегляд</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="uk">
      <configuration name="person_can_view_child_form_user_map" locale="uk"></configuration>
      <configuration name="person_can_edit_child_form_user_map" locale="uk"></configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="user_map">
          <configuration name="display" values="single" locale="uk">
            <value>Карта користувача</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_UserMap">
          <configurationGroup name="fields">
            <configurationGroup name="username">
              <configuration name="headers" type="delimited" locale="uk">
                <value>default:Ім'я користувача</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="page" path="/modules/SelfService/page">
      <configurationGroup name="userAccount">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="uk">
            <value>Додати/оновити обліковий запис користувача</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Currency/configs/de/Currency.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Currency" path="/I2CE">
  <metadata>
    <version>4.3.3.0.1</version>
  </metadata>
  <configurationGroup name="Currency" path="/I2CE" locale="de">
    <version>4.3.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="de">
      <configuration name="can_edit_database_list_currency" locale="de">
        <value>Kann Währungsinformationen bearbeiten</value>
      </configuration>
      <configuration name="can_view_database_list_currency" locale="de">
        <value>Kann Währungsinformationen ansehen</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="currency">
          <configuration name="display" values="single" locale="de">
            <value>Währung</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Currency">
          <configurationGroup name="fields">
            <configurationGroup name="code">
              <configuration name="headers" type="delimited" locale="de">
                <value>default:Währungskennung</value>
                <value>title:Der internationale Währungscode (z. B. „USD“, „EUR“, usw.).</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="name">
              <configuration name="headers" type="delimited" locale="de">
                <value>title:z. B. „US-Dollar“, „Euro“</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="country">
              <configuration name="headers" type="delimited" locale="de">
                <value>default:Staat</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="symbol">
              <configuration name="headers" type="delimited" locale="de">
                <value>title:z. B. „$“, „€“</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/Education/configs/pt_BR/Education.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonEducation" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonEducation" path="/I2CE" locale="pt_BR">
    <version>4.2.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="pt_BR">
      <configuration name="person_can_view_child_form_education" locale="pt_BR"></configuration>
      <configuration name="person_can_edit_child_form_education" locale="pt_BR"></configuration>
      <configuration name="can_edit_database_list_edu_type" locale="pt_BR"></configuration>
      <configuration name="can_view_database_list_edu_type" locale="pt_BR"></configuration>
      <configuration name="can_edit_database_list_degree" locale="pt_BR"></configuration>
      <configuration name="can_view_database_list_degree" locale="pt_BR"></configuration>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="education">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="pt_BR">
            <value>Adicionar/Atualizar Histórico Educacional</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="degree">
          <configuration name="display" values="single" locale="pt_BR">
            <value>Grau</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="edu_type">
          <configuration name="display" values="single" locale="pt_BR">
            <value>Tipo de Educação</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="education">
          <configuration name="display" values="single" locale="pt_BR">
            <value>Histórico Educacional</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Degree">
          <configurationGroup name="fields">
            <configurationGroup name="name">
              <configuration name="headers" type="delimited" locale="pt_BR">
                <value>default:Nome</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="edu_type">
              <configuration name="headers" type="delimited" values="many" locale="pt_BR">
                <value>default:Tipo de Educação</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="iHRIS_Education">
          <configurationGroup name="fields">
            <configurationGroup name="degree">
              <configuration name="headers" type="delimited" locale="pt_BR">
                <value>default:Grau</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="institution">
              <configuration name="headers" type="delimited" locale="pt_BR">
                <value>default:Nome da Instituição</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="location">
              <configuration name="headers" type="delimited" locale="pt_BR">
                <value>default:Localização da Instituição</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="year">
              <configuration name="headers" type="delimited" locale="pt_BR">
                <value>default:Ano de Graduação (Deixe em branco se ainda não houver completado)</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="major">
              <configuration name="headers" type="delimited" locale="pt_BR"></configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/Forms/modules/Lists/modules/WebServicesLists/configs/en_US/WebServicesLists.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="web-services-lists" path="/modules/web-services">
  <metadata>
    <version>4.3.0</version>
  </metadata>
  <configurationGroup name="web-services-lists" path="/modules/web-services" locale="en_US">
    <version>4.3.0</version>
    <configurationGroup name="messages" locale="en_US">
      <configuration name="invalid_list" values="single" type="string">
        <value>That is not a valid list: '%s'</value>
      </configuration>
      <configuration name="invalid_form" values="single" type="string">
        <value>That is not a valid form '%s'</value>
      </configuration>
      <configuration name="invalid_field" values="single" type="string">
        <value>That is not a valid field '%s' in form '%s'</value>
      </configuration>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Photo/configs/sw/Photo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Photo" path="/I2CE">
  <metadata>
    <version>4.3.0.1</version>
  </metadata>
  <configurationGroup name="Photo" path="/I2CE" locale="sw">
    <version>4.3.0.1</version>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Photo">
          <configurationGroup name="fields">
            <configurationGroup name="image">
              <configuration name="headers" type="delimited" locale="sw">
                <value>default:Taswira</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="date">
              <configuration name="headers" type="delimited" locale="sw">
                <value>default:Tarehe</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="description">
              <configuration name="headers" type="delimited" values="many" locale="sw">
                <value>default:Ufafanuzi</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Currency/configs/so/Currency.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Currency" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="Currency" path="/I2CE" locale="so">
    <version>4.2.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="so">
      <configuration name="can_edit_database_list_currency" locale="so">
        <value>Waxaa suura gal ah inaad badashid macluumaadka lacagta</value>
      </configuration>
      <configuration name="can_view_database_list_currency" locale="so">
        <value>Waxaad soo bandhigi kartaa macluumaad ku saabsan lacagta</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="currency">
          <configuration name="display" values="single" locale="so">
            <value>Lacag</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Currency">
          <configurationGroup name="fields">
            <configurationGroup name="code">
              <configuration name="headers" type="delimited" locale="so">
                <value>default:Sumadda lacagta</value>
                <value>title:Sumadda lacagta dibadaha (tusaale:"USD", "GBP", IWL.)</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="name">
              <configuration name="headers" type="delimited" locale="so">
                <value>default:Magac</value>
                <value>title:Tusaale. "Doollar mareeykan" "Gani Biritin"</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="country">
              <configuration name="headers" type="delimited" locale="so">
                <value>default:Dalka</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="symbol">
              <configuration name="headers" type="delimited" locale="so">
                <value>default:Sumad</value>
                <value>title:Tusaale. "$"</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/Employment/configs/br/Employment.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonEmployment" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonEmployment" path="/I2CE" locale="br">
    <version>4.2.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="br">
      <configuration name="person_can_view_child_form_employment" locale="br">
        <value>A c'hall diskwel furmskrid bugel chemet micherel un den</value>
      </configuration>
      <configuration name="person_can_edit_child_form_employment" locale="br">
        <value>A c'hall kemmañ furmskridoù bugel chemet un den</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="employment">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="br">
            <value>Ouzhpennañ/hizivaat ar chemet micherel</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="employment">
          <configuration name="display" values="single" locale="br">
            <value>Chemet micherel</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Employment">
          <configurationGroup name="fields">
            <configurationGroup name="company_name">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Anv ar c'hevredad</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="company_address">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Chomlec'h ar c'hevredad</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="company_phone">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Pellgomz ar c'henvredad</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="start_date">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Deiziad kregiñ</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="start_wage">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Gopr deroù</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="start_position">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Post deroù</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="end_date">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Deiziad dibenn (chom hep kargañ ma vez implijet c'hoazh)</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="end_wage">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Gopr diwezhañ</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="end_position">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Post diwezhañ</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="supervisor">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Gourseller</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="contact_ok">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Ha gallout a reer mont e darempred gantañ?</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="responsibilities">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Atebegezhioù stag ouzh ar post</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="reason_for_leaving">
              <configuration name="headers" type="delimited" locale="br">
                <value>default:Abegoù an disparti</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>
