=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/lib/I2CE_Configuration.dtd
<!ELEMENT I2CEConfiguration (metadata,(eraseVals|erase)*,configurationGroup?)>
<!ATTLIST I2CEConfiguration name NMTOKEN #REQUIRED>
<!ELEMENT metadata
          (displayName,className?,category?,description?,longDescription?,creator?,email?,link?,version,(enable|requirement|conflict|path)*,priority?)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ELEMENT path (value*)>
<!ATTLIST path name NMTOKEN #REQUIRED>
<!ELEMENT enable EMPTY>
<!ATTLIST enable name NMTOKEN #REQUIRED>
<!ELEMENT requirement (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST requirement name NMTOKEN #REQUIRED>
<!ATTLIST requirement external NMTOKEN #IMPLIED>
<!ELEMENT conflict (atLeast|atMost|exactly|greaterThan|lessThan|eval)*>
<!ATTLIST conflict name NMTOKEN #REQUIRED>
<!ATTLIST conflict external NMTOKEN #IMPLIED>
<!ELEMENT erase (atLeast|atMost|exactly|greaterThan|lessThan)>
<!ATTLIST erase path CDATA #REQUIRED>
<!ELEMENT eraseVals ((atLeast|atMost|exactly|greaterThan|lessThan),value*) >
<!ATTLIST eraseVals path CDATA #REQUIRED>
<!ELEMENT configurationGroup (displayName?,description?,version?,status*,(configurationGroup|configuration|eraseVals|erase)*)>
<!ATTLIST configurationGroup name NMTOKEN  #REQUIRED>
<!ATTLIST configurationGroup path CDATA #IMPLIED>
<!ATTLIST configurationGroup config NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup locale NMTOKEN #IMPLIED>
<!ATTLIST configurationGroup binary NMTOKEN #IMPLIED>
<!ELEMENT configuration (displayName?,description?,version?,status*,value*,(eraseVals|erase)*)>
<!ATTLIST configuration name NMTOKEN #REQUIRED>
<!ATTLIST configuration path CDATA #IMPLIED>
<!ATTLIST configuration values NMTOKEN "single">
<!ATTLIST configuration type NMTOKEN "string">
<!ATTLIST configuration config NMTOKEN #IMPLIED>
<!ATTLIST configuration locale NMTOKEN #IMPLIED>
<!ATTLIST configuration binary NMTOKEN #IMPLIED>
<!ATTLIST configuration encoding NMTOKEN #IMPLIED>
<!ELEMENT displayName (#PCDATA)>
<!ATTLIST displayName locale NMTOKEN #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT longDescription (#PCDATA)>
<!ATTLIST longDescription locale NMTOKEN #IMPLIED>
<!ATTLIST description locale NMTOKEN #IMPLIED>
<!ELEMENT className (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category locale NMTOKEN #IMPLIED>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT value (#PCDATA)> 
<!ATTLIST value locale NMTOKEN #IMPLIED>
<!ELEMENT eval EMPTY> 
<!ELEMENT atLeast EMPTY> 
<!ATTLIST atLeast version CDATA #REQUIRED>
<!ELEMENT greaterThan EMPTY> 
<!ATTLIST greaterThan version CDATA #REQUIRED>
<!ELEMENT atMost EMPTY> 
<!ATTLIST atMost version CDATA #REQUIRED>
<!ELEMENT lessThan EMPTY> 
<!ATTLIST lessThan version CDATA #REQUIRED> 
<!ELEMENT exactly EMPTY> 
<!ATTLIST exactly version CDATA #REQUIRED>
<!ELEMENT visibility (#PCDATA)> 
<!ELEMENT status (#PCDATA)>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/ID/configs/pa/ID.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonID" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonID" path="/I2CE" locale="pa">
    <version>4.2.1.0.1</version>
    <configurationGroup name="invalid_formfield_message" path="/modules/forms/formfield_messages" locale="pa">
      <configuration name="exp_date" path="person_id/expiration_date/bad_date" locale="pa"></configuration>
      <configuration name="wrong_pattern" path="person_id/id_num/wrong_pattern" locale="pa"></configuration>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="pa">
      <configuration name="person_can_view_child_form_person_id" locale="pa"></configuration>
      <configuration name="person_can_edit_child_form_person_id" locale="pa"></configuration>
      <configuration name="can_edit_database_list_id_type" locale="pa"></configuration>
      <configuration name="can_view_database_list_id_type" locale="pa"></configuration>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="person_id">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="pa">
            <value>ਸ਼ਨਾਖ਼ਤ ਜੋੜੋ/ਨਵਿਆਉ</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms/forms">
      <configurationGroup name="id_type">
        <configuration name="display" values="single" locale="pa">
          <value>ਸ਼ਨਾਖ਼ਤ ਦੀ ਕਿਸਮ</value>
        </configuration>
      </configurationGroup>
      <configurationGroup name="person_id">
        <configuration name="display" values="single" locale="pa">
          <value>ਨਿੱਜੀ ਸ਼ਨਾਖ਼ਤ</value>
        </configuration>
        <configurationGroup name="meta">
          <configuration name="description" locale="pa"></configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms/formClasses">
      <configurationGroup name="iHRIS_PersonID">
        <configurationGroup name="fields">
          <configurationGroup name="id_type">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਸ਼ਨਾਖ਼ਤ ਦੀ ਕਿਸਮ</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="id_num">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਸ਼ਨਾਖ਼ਤੀ ਨੰਬਰ</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="issue_date">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਕੱਢਣ ਦੀ ਮਿਤੀ</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="expiration_date">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਮਿਆਦ ਮੁੱਕਣ ਦੀ ਮਿਤੀ</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="country">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਕੱਢਣ ਵਾਲ਼ਾ ਮੁਲਕ</value>
            </configuration>
          </configurationGroup>
          <configurationGroup name="place">
            <configuration name="headers" type="delimited" locale="pa">
              <value>default:ਕੱਢਣ ਦਾ ਟਿਕਾਣਾ</value>
            </configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="iHRIS_PersonID_Type">
        <configurationGroup name="fields">
          <configurationGroup name="pattern">
            <configuration name="headers" type="delimited" locale="pa"></configuration>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/Contact/configs/it/Contact.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonContact" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonContact" path="/I2CE" locale="it">
    <version>4.2.0.1</version>
    <configurationGroup name="invalid_messages" path="/modules/forms/formfield_messages" locale="it">
      <configuration name="work" path="work/email/invalid_email">
        <value>Per favore inserisci un indirizzo email valido</value>
      </configuration>
      <configuration name="personal" path="personal/email/invalid_email">
        <value>Per favore inserisci un indirizzo email valido</value>
      </configuration>
      <configuration name="other" path="other/email/invalid_email">
        <value>Per favore inserisci un indirizzo email valido</value>
      </configuration>
      <configuration name="emergency" path="emergency/email/invalid_email">
        <value>Per favore inserisci un indirizzo email valido</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="it">
      <configuration name="person_can_view_child_form_person_contact_work" locale="it">
        <value>Visualizza il sottomodulo del contatto di lavoro di una persona</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_contact_work" locale="it">
        <value>Modifica il sottomodulo del contatto di lavoro di una persona</value>
      </configuration>
      <configuration name="person_can_view_child_form_person_contact_emergency" locale="it">
        <value>Visualizza il sottomodulo del contatto d'emergenza di una persona</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_contact_emergency" locale="it">
        <value>Modifica il sottomodulo del contatto d'emergenza di una persona</value>
      </configuration>
      <configuration name="person_can_view_child_form_person_contact_personal" locale="it">
        <value>Visualizza il sottomodulo del contatto personale di una persona</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_contact_personal" locale="it">
        <value>Modifica il sottomodulo del contatto personale di una persona</value>
      </configuration>
      <configuration name="person_can_view_child_form_person_contact_other" locale="it">
        <value>Visualizza il sottomodulo degli altri contatti di una persona</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_contact_other" locale="it">
        <value>Modifica il sottomodulo degli altri contatti di una persona</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="person_contact_work">
          <configuration name="display" values="single" locale="it">
            <value>Contatto lavorativo</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="person_contact_emergency">
          <configuration name="display" values="single" locale="it">
            <value>Contatto per emergenze</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="person_contact_other">
          <configuration name="display" values="single" locale="it">
            <value>Altro contatto</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="person_contact_personal">
          <configuration name="display" values="single" locale="it">
            <value>Contatto personale</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="contact">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="it">
            <value>Aggiungi/aggiorna le informazioni sui contatti</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/i2ce/modules/Pages/modules/LocaleSelector/configs/zh_CN/LocaleSelector.xml
<?xml version="1.0"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="localeSelector">
  <metadata>
    <displayName>Locale Selector</displayName>
    <className>I2CE_Module_LocaleSelector</className>
    <version>4.3.0</version>
  </metadata>
  <configurationGroup name="localeSelector" locale="zh_CN">
    <configuration name="languages" path="/locales/languages" values="many" type="delimited">
      <version>4.0.0</version>
      <value>aa:阿法尔语</value>
      <value>ab:阿布哈西亚语</value>
      <value>ae:阿维斯陀语</value>
      <value>af:南非荷兰语</value>
      <value>am:阿姆哈拉语</value>
      <value>ar:阿拉伯语</value>
      <value>as:阿萨姆语</value>
      <value>ay:艾马拉语</value>
      <value>az:阿塞拜疆语</value>
      <value>ba:巴什基尔语</value>
      <value>be:白俄罗斯语</value>
      <value>bg:保加利亚语</value>
      <value>bh:比哈里语</value>
      <value>bi:比斯拉马语</value>
      <value>bn:孟加拉语</value>
      <value>bo:藏语</value>
      <value>br:布里多尼语</value>
      <value>bs:波斯尼亚语</value>
      <value>ca:加泰罗尼亚语</value>
      <value>ce:车臣语</value>
      <value>ch:查莫罗语</value>
      <value>co:科西嘉语</value>
      <value>cs:捷克语</value>
      <value>cu:宗教斯拉夫语(古代俄语)</value>
      <value>cv:楚瓦什语</value>
      <value>cy:威尔士</value>
      <value>da:丹麦语</value>
      <value>de:德语</value>
      <value>dz:不丹宗卡语</value>
      <value>el:希腊语</value>
      <value>en:英语</value>
      <value>en_GB:英国英语</value>
      <value>en_US:美国英语</value>
      <value>eo:世界语</value>
      <value>es:西班牙语</value>
      <value>et:爱沙尼亚语</value>
      <value>eu:巴斯克语</value>
      <value>fa:波斯语</value>
      <value>fi:芬兰语</value>
      <value>fj:斐济语</value>
      <value>fo:法罗群岛语</value>
      <value>fr:法语</value>
      <value>fy:弗里斯兰语</value>
      <value>ga:爱尔兰盖尔语</value>
      <value>gd:盖尔语</value>
      <value>gl:加利西亚语</value>
      <value>gn:瓜拉尼语</value>
      <value>gu:古吉拉特语</value>
      <value>gv:马恩岛语</value>
      <value>ha:豪撒语</value>
      <value>he:希伯来语</value>
      <value>hi:北印度语</value>
      <value>ho:新里木托语</value>
      <value>hr:克罗地亚语</value>
      <value>hsb:索布语</value>
      <value>hu:匈牙利语</value>
      <value>hy:亚美尼亚语</value>
      <value>hz:赫雷罗语</value>
      <value>ia:拉丁国际语(国际辅助语)</value>
      <value>id:印度尼西亚语</value>
      <value>ie:语际语</value>
      <value>ik:因纽佩特语</value>
      <value>io:伊多语</value>
      <value>is:冰岛语</value>
      <value>it:意大利语</value>
      <value>iu:因纽特语</value>
      <value>ja:日语</value>
      <value>jv:爪哇语</value>
      <value>ka:乔治亚语</value>
      <value>ki:基库尤语</value>
      <value>kk:哈萨克语</value>
      <value>kl:格陵兰语</value>
      <value>km:高棉语</value>
      <value>kn:坎纳德语</value>
      <value>ko:朝鲜语</value>
      <value>ks:克什米尔语</value>
      <value>ku:库尔德语</value>
      <value>kv:科米语</value>
      <value>kw:康瓦尔郡语</value>
      <value>ky:吉尔吉斯语</value>
      <value>la:拉丁语</value>
      <value>lb:卢森堡语</value>
      <value>li:林堡语</value>
      <value>ln:林加拉语</value>
      <value>lo:老挝语</value>
      <value>lt:立陶宛语</value>
      <value>lv:拉脱维亚语</value>
      <value>mg:马尔加什语</value>
      <value>mh:马绍尔语</value>
      <value>mi:毛利语</value>
      <value>mk:马其顿语</value>
      <value>ml:德拉维族语</value>
      <value>mn:蒙古语</value>
      <value>mo:摩尔多瓦</value>
      <value>mr:马拉地语</value>
      <value>ms:马来西亚语</value>
      <value>mt:马耳他语</value>
      <value>my:缅甸语</value>
      <value>na:瑙鲁语</value>
      <value>nb:挪威语 (博克马尔语)</value>
      <value>nd:Ndebele，北部</value>
      <value>nds:撒克逊语</value>
      <value>ne:尼泊尔语</value>
      <value>nl:荷兰语</value>
      <value>nn:挪威语 (尼诺斯克语)</value>
      <value>nr:Ndebele，南部</value>
      <value>nso:北部梭托语</value>
      <value>nv:纳瓦霍语</value>
      <value>ny:齐切瓦语</value>
      <value>oc:奥西坦语</value>
      <value>om:阿曼语</value>
      <value>or:欧里亚语</value>
      <value>os:奥塞梯语</value>
      <value>pa:旁遮普语</value>
      <value>pi:巴利语</value>
      <value>pl:波兰语</value>
      <value>ps:普什图语</value>
      <value>pt:葡萄牙语</value>
      <value>pt_BR:巴西葡萄牙语</value>
      <value>qu:盖丘亚语</value>
      <value>rn:基隆迪语</value>
      <value>ro:罗马尼亚语</value>
      <value>rom:吉普赛语</value>
      <value>ru:俄语</value>
      <value>rw:卢旺达语</value>
      <value>sa:梵语</value>
      <value>sc:撒丁语</value>
      <value>se:北部沙米语</value>
      <value>sg:桑戈语</value>
      <value>si:僧伽罗语</value>
      <value>sk:斯洛伐克语</value>
      <value>sl:斯洛文尼亚语</value>
      <value>sm:萨摩亚语</value>
      <value>sn:修纳语</value>
      <value>so:索马里语</value>
      <value>sq:阿尔巴尼亚语</value>
      <value>sr:塞尔维亚语(拉丁)</value>
      <value>ss:斯瓦特语</value>
      <value>st:索托，南部</value>
      <value>su:巽他语</value>
      <value>sv:瑞典语</value>
      <value>sw:斯瓦希里语</value>
      <value>ta:泰米尔语</value>
      <value>te:泰卢固语</value>
      <value>tg:塔吉克语</value>
      <value>th:泰语</value>
      <value>ti:提格里尼亚语</value>
      <value>tk:土库曼语</value>
      <value>tn:茨瓦纳语</value>
      <value>to:汤加语</value>
      <value>tr:土耳其语</value>
      <value>ts:特松加语</value>
      <value>tt:鞑靼语</value>
      <value>tw:契维语</value>
      <value>ty:塔希提语</value>
      <value>ug:维吾尔语</value>
      <value>uk:乌克兰语</value>
      <value>ur:乌尔都语</value>
      <value>uz:乌兹别克语</value>
      <value>ven:闻达语</value>
      <value>vi:越南语</value>
      <value>vo:沃拉普克语</value>
      <value>wa:瓦龙语</value>
      <value>wo:沃洛夫语</value>
      <value>xh:科萨语</value>
      <value>yi:依地语</value>
      <value>yo:约鲁巴语</value>
      <value>za:壮语</value>
      <value>zh:中文</value>
      <value>zh_CN:简体中文</value>
      <value>zh_HK:繁体中文(香港)</value>
      <value>zh_TW:繁体中文</value>
      <value>zu:祖鲁语</value>
    </configuration>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Contact/configs/lt/Contact.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="Contact" path="/I2CE">
  <metadata>
    <version>4.2.1.2.1</version>
  </metadata>
  <configurationGroup name="Contact" path="/I2CE" locale="lt">
    <version>4.2.1.2.1</version>
    <configurationGroup name="/modules/forms/forms/contact_group">
      <configuration name="display" values="single" locale="lt">
        <value>Kontaktų grupė</value>
      </configuration>
      <configurationGroup name="meta">
        <configuration name="description" locale="lt">
          <value>Kontaktų grupių sąrašas</value>
        </configuration>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="/modules/forms/formClasses/iHRIS_Contact/fields/contact_group">
      <configuration name="headers" type="delimited" locale="lt">
        <value>default:Kontaktų grupės</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Contact">
          <configurationGroup name="fields">
            <configurationGroup name="address">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Pašto adresas</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="telephone">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Telefono numeris</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="mobile_phone">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Mobiliojo telefono numeris</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="alt_telephone">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Alternatyvus telefono numeris</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="fax">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Fakso numeris</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="email">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:E-pašto adresas:</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="notes">
              <configuration name="headers" type="delimited" values="many" locale="lt">
                <value>default:Pastabos</value>
                <value>contact_person:Pastabos (pirminis kontaktinis asmuo)</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
        <configurationGroup name="iHRIS_NamedContact">
          <configurationGroup name="fields">
            <configurationGroup name="name">
              <configuration name="headers" type="delimited" locale="lt">
                <value>default:Vardas</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/SimpleComptency/configs/sw/SimpleCompetency.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="simple-competency" path="/I2CE">
  <metadata>
    <version>4.3.0.1</version>
  </metadata>
  <configurationGroup name="simple-competency" path="/I2CE" locale="sw">
    <version>4.3.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description">
      <configuration name="can_edit_database_lists_competency" locale="sw">
        <value>Hariri orodha zote zinazohusiana na uwezo</value>
      </configuration>
      <configuration name="can_edit_database_list_competency" locale="sw">
        <value>Hariri orodha ya uwezo</value>
      </configuration>
      <configuration name="can_edit_database_list_competency_type" locale="sw">
        <value>Hariri orodha ya aina ya uwezo</value>
      </configuration>
      <configuration name="can_view_database_lists_competency" locale="sw">
        <value>Angalia orodha zote zinazohusiana na uwezo</value>
      </configuration>
      <configuration name="can_view_database_list_competency" locale="sw">
        <value>Angalia orodha ya uwezo</value>
      </configuration>
      <configuration name="can_view_database_list_competency_type" locale="sw">
        <value>Angalia orodha ya aina ya uwezo</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="competency">
          <configuration name="display" values="single" locale="sw">
            <value>Uwezo</value>
          </configuration>
        </configurationGroup>
        <configurationGroup name="competency_type">
          <configuration name="display" values="single" locale="sw">
            <value>Aina ya Uwezo</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
      <configurationGroup name="formClasses">
        <configurationGroup name="iHRIS_Competency">
          <configurationGroup name="fields">
            <configurationGroup name="name">
              <configuration name="headers" type="delimited" locale="sw">
                <value>default:Jina</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="competency_type">
              <configuration name="headers" type="delimited" values="many" locale="sw">
                <value>default:Aina ya Uwezo</value>
                <value>select_competency_type:Chagua Aina ya Uwezo halafu Uwezo</value>
              </configuration>
            </configurationGroup>
            <configurationGroup name="notes">
              <configuration name="headers" type="delimited" locale="sw">
                <value>default:Maelezo</value>
              </configuration>
            </configurationGroup>
          </configurationGroup>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/CommonSampleData/modules/SampleData-currency/configs/fr_ML/SampleData-currency.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="SampleData-currency" path="//I2CE/formsData/forms/currency">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="SampleData-currency" path="//I2CE/formsData/forms/currency" locale="fr_ML">
    <version>4.2.0.1</version>
    <configurationGroup name="2">
      <configurationGroup name="fields">
        <configuration name="name" locale="fr_ML"></configuration>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="3">
      <configurationGroup name="fields">
        <configuration name="name" locale="fr_ML">
          <value>Dollar Americain</value>
        </configuration>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="4">
      <configurationGroup name="fields">
        <configuration name="name" locale="fr_ML">
          <value>Livre Sterling</value>
        </configuration>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Job/modules/who_cadre/configs/pt_BR/who-cadre.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="who_cadre" path="/">
  <metadata>
    <version>4.3.0.1</version>
  </metadata>
  <configurationGroup name="who_cadre" path="/" locale="pt_BR">
    <version>4.3.0.1</version>
    <configurationGroup name="who_cadre_form" path="/modules/forms/forms/who_cadre">
      <configuration name="display" locale="pt_BR">
        <value>Cadre (OMS)</value>
      </configuration>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>

=== agabaandre/iHRIS-Pharmacy-Qualify/4.1.11/ihris-common/modules/Person/modules/PersonPhoto/configs/sk/PersonPhoto.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE I2CEConfiguration SYSTEM "I2CE_Configuration.dtd">
<I2CEConfiguration name="PersonPhoto" path="/I2CE">
  <metadata>
    <version>4.2.1.0.1</version>
  </metadata>
  <configurationGroup name="PersonPhoto" path="/I2CE" locale="sk">
    <version>4.2.0.1</version>
    <configurationGroup name="tasks" path="/I2CE/tasks/task_description" locale="sk">
      <configuration name="person_can_view_child_form_person_photo_passport" locale="sk">
        <value>možno zobraziť osobnú fotografiu z pasu</value>
      </configuration>
      <configuration name="person_can_edit_child_form_person_photo_passport" locale="sk">
        <value>Možno upraviť osobnú fotografiu z pasu</value>
      </configuration>
    </configurationGroup>
    <configurationGroup name="forms" path="/modules/forms">
      <configurationGroup name="forms">
        <configurationGroup name="person_photo_passport">
          <configuration name="display" values="single" locale="sk">
            <value>Fotografia osoby</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
    <configurationGroup name="page">
      <configurationGroup name="person_photo_passport">
        <configurationGroup name="args">
          <configuration name="title" values="single" locale="sk">
            <value>pridaj/Aktualizuj pasovú fotografiu</value>
          </configuration>
        </configurationGroup>
      </configurationGroup>
    </configurationGroup>
  </configurationGroup>
</I2CEConfiguration>
